
version: '3.7'
services:
  tf-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./serving/interests-model/1:/models/interests-model/1
    environment:
      MODEL_NAME: interests-model
